# Use the official Node.js image as the base image
FROM node:16

# Install Python 3 and other dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        python3-dev \
        build-essential \
        wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Prep directories copy files
COPY Parser_Module/ /app/Parser_Module/
COPY WebSocket_Backend/ /app/WebSocket_Backend/
COPY WebSocket_Backend/ /app/WebSocket_Backend/
COPY react_frontend/ /app/react_frontend/

# Install Node.js dependencies for the React app
RUN cd /app/react_frontend/ && npm install


# update pip

RUN pip3 install --upgrade pip
run which python3

# Python requirements install
RUN pip3 install --no-cache-dir -r /app/WebSocket_Backend/requirements.txt

# Expose the port the app runs on
EXPOSE 3000
EXPOSE 5000


# Start both the Python and Node.js applications
CMD ["sh", "-c", "python3 /app/Parser_Module/parse.py & node /app/WebSocket_Backend/server.js & python3 /app/WebSocket_Backend/websocket.py & cd /app/react_frontend/ && npm start"]