

# Use the official MongoDB base image
FROM mongo:latest

# Optional: Set environment variables (e.g., root user credentials)
# ENV MONGO_INITDB_ROOT_USERNAME=<your-username>
# ENV MONGO_INITDB_ROOT_PASSWORD=<your-password>

# Expose MongoDB's default port
EXPOSE 27017

# Define a command that starts MongoDB
CMD ["mongod"]
